### ISSUE TITLE
MemoryStreams are not disposed

### ISSUE THREAD

**Issue by kemsky** [EPPlusSoftware/EPPlus#1103]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

MacOS

### Epplus version

6.2.10

### Description

`RecyclableMemoryStream` should be disposed otherwise object will go through finalizer, it generates pressure on GC and exhausts stream pool. EPPlus creates a lot of `RecyclableMemoryStream`s (about 10 for a single load operation) and most of them are not disposed correctly. #832 might be related.

`RecyclableMemoryStreamManager` provides event source to monitor such cases,  and allows to enable capturing callstacks for stream allocations with `GenerateCallStacks` property.

You can use the following listener to inspect the problem (you might need to trigger GC or disable server GC):

```csharp
public sealed class MemoryStreamEventListener : EventListener
{
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        if (eventSource.Name == "Microsoft-IO-RecyclableMemoryStream")
        {
            var args = new Dictionary<string, string>
            {
                ["EventCounterIntervalSec"] = "1"
            };

            EnableEvents(eventSource, EventLevel.Verbose, EventKeywords.All, args);
        }
    }

    protected override void OnEventWritten(EventWrittenEventArgs eventWrittenEventArgs)
    {
        if (string.Equals("MemoryStreamFinalized", eventWrittenEventArgs.EventName, StringComparison.Ordinal))
        {
            var args = eventWrittenEventArgs.Payload?.Where(x => x != null).ToList() ?? new List<object>();

            var stacktrace = args.FirstOrDefault(x => x is string s && s.StartsWith("   at System.Environment.get_StackTrace()", StringComparison.Ordinal)) as string;

            var message = string.Join(", ", args.Where(x => !(x is string s && s.StartsWith("   at System.Environment.get_StackTrace()", StringComparison.Ordinal))));

            Console.WriteLine($"[{eventWrittenEventArgs.EventName}] {message}");
        }
    }
}
```

**Comment by JanKallman** [comment]
We have fixed this issue in EPPLus 7 See this commit - https://github.com/EPPlusSoftware/EPPlus/commit/b11ab3979946ba2da0e3d48f5f8dcece5aef767d
It is included in EPPlus 7-rc1, if you want to test it.
We aim for releasing EPPlus 7 later this week.
I will try to add a fix for this in the next release of EPPlus 6 as well.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.0.0 and 6.2.11

**Comment by kemsky** [comment]
@JanKallman, some streams are still not disposed (I'm using 6.2.11), stack traces:

```
   at OfficeOpenXml.WorksheetZipStream.SetWriteToBuffer()
   at OfficeOpenXml.ExcelWorksheet.LoadExtLst(XmlReader xr, WorksheetZipStream stream, String& xml, String& lastXmlElement)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
```

```
   at OfficeOpenXml.WorksheetZipStream..ctor(Stream zip, Boolean writeToBuffer, Int64 size)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
```

```
   at OfficeOpenXml.Packaging.ZipPackage.ExtractEntryToPart(ZipInputStream zip, ZipEntry e)
   at OfficeOpenXml.Packaging.ZipPackage..ctor(Stream stream)
   at OfficeOpenXml.ExcelPackage.Load(Stream input, Stream output, String Password)
   at OfficeOpenXml.ExcelPackage.Load(Stream input)
   at OfficeOpenXml.ExcelPackage..ctor(Stream newStream)
```

```
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
```

```
   at OfficeOpenXml.ExcelPackage.Load(Stream input)
   at OfficeOpenXml.ExcelPackage..ctor(Stream newStream)
```

**Comment by JanKallman** [comment]
Thanks, we'll have another look.

**Comment by JanKallman** [comment]
I have added a few more fixes for this issue in 6.2.12 and 7.0.1.
I will leave this issue open and do some additional checks to verify that all MemoryStream's are disposed correctly for the next version.

**Comment by kemsky** [comment]
@JanKallman, I've made some tests using latest version, looks good, thank you.

**Comment by JanKallman** [comment]
This should now be fixed in 6.2.12 & 7.0.2
