### ISSUE TITLE
Workbook loses formatting after saving with EPPlus

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#294]
Hello,

Using version 5.5.2 of EPPlus, after saving an existing workbook with EPPlus we observe a warning that the workbook needs to be repaired.  After clicking "Yes" to the repair prompt, the workbook opens but all formatting is lost.

I attached 2 workbooks:
test_excel_workbook_before.xlsx:  workbook before saving with EPPlus
test_excel_workbook_after.xlsx:  workbook after saving with EPPlus (notice the repair message and lost formatting)

All we are doing is inserting a worksheet into the existing workbook and writing some data to that new worksheet:

ExcelWorksheet ws = wb.Worksheets.Add(name);
//write some data to the new worksheet
wb.SaveAs(filename);

**Comment by rdhasse** [comment]
[test_excel_workbook_before.zip](https://github.com/EPPlusSoftware/EPPlus/files/5904364/test_excel_workbook_before.zip)
[test_excel_workbook_after.zip](https://github.com/EPPlusSoftware/EPPlus/files/5904366/test_excel_workbook_after.zip)

**Comment by JanKallman** [comment]
The "before" file is corrupt when you to open it in Excel. Also, it contains 53 000 named styles making it quite hard to troubleshot.

**Comment by rdhasse** [comment]
I can open the "before" file just fine without any error message.  We are using Office 365 (Microsoft Excel for Microsoft 365 MSO (16.0.13127.21062) 64-bit).  Is there anything we can do to make it easier to debug?

**Comment by JanKallman** [comment]
I get this error...
![image](https://user-images.githubusercontent.com/982881/106616768-341c2600-656e-11eb-8059-d10527040b99.png)
I'll have a look if I can narrow it down, but finding the issue in a workbook with 11M styles.xml might be tricky. The issue is likely with the 53 000 named styles.

**Comment by JanKallman** [comment]
I found the issue. As this workbook has more than 32K styles, the format EPPlus uses does not support that. Newer versions of Excel adds an URI to the cellStyle records for example, xr:uid="{00000000-0005-0000-0000-000007CD0000}" and possibly some other things. 
I will look more into this and add a fix in a coming version, but it might take some time.

**Comment by rdhasse** [comment]
I assume you will post an update here if/when a fix for this issue is released?  We've seen this issue a few times so some people are eager to have it resolved.

**Comment by JanKallman** [comment]
This in more like a limitation of EPPlus right now. It happens when you have workbooks with more than 32 000 named styles. 
As I assume this is not that common and it requires new functionality to be implemented, we haven't given it that high attention.
Do you have a lot of workbook that have exceeds this limit?

**Comment by EmaGht** [comment]
I found that latest version 4.X of EPPLUS actually works without any problem, i guess there must have been some changes to style handlings in newer versions, but yea this is definitely an issue that would be nice to see resolved

**Comment by JanKallman** [comment]
This issue should be fixed in EPPlus 5.6.

**Comment by EmaGht** [comment]
@JanKallman unfortunately i'm still seeing this error on version 5.6.1. I can privately send you my excel file for further analysis if you want
