### ISSUE TITLE
EPPlus 6.1.0 ExcelTable sorting destroys relative formulas

### ISSUE THREAD

**Issue by konijntje2** [EPPlusSoftware/EPPlus#746]
When you use relative formulas on ExcelTable like this:
ws.Cells[currentRow, lastWeekColumn + 1].Formula = "Table1[[#This Row],[" + currentWeekString + "]]-Table1[[#This Row],[" + previousWeekString + "]]";

And then you do sorting like this:
table.SortState.Clear();
table.Sort(x => x.SortBy.Column(lastWeekColumn, eSortOrder.Descending));

Then the above formula is not resolved to =[@[2022/45]]-[@[2022/44]] but to # not valid reference
When we leave the sorting the above formula is well parsed...

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this.

**Comment by swmal** [comment]
This has now been fixed in our develop branch and you can test it via our development nuget feed when the current build is completed.

https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by JanKallman** [comment]
Fixed in 6.1.1

**Comment by konijntje2** [comment]
Thank you for regarding this.

There is still an issue, when you sort on a column that contains relative fomulas that equals positive and negatie numbers and blanks.
Then, the sorting is not working and the file gets corrupted.

eg : =[@[2022/47]]-[@[2022/46]]
which give values
-1.25
2.48
blank
-3
4.32
is not sorting...
